### ISSUE TITLE
Repeated assoc-in gives NPE

### ISSUE THREAD

**Issue by borkdude** [borkdude/rewrite-edn#19]
Repro:

```
(-> (r/parse-string "{}") (r/assoc-in [:deps 'foo] {:mvn/version "x"}) (r/assoc-in [:deps 'bar] {:mvn/version "y"}) str)
``` 

A workaround is to insert `str r/parse-str` in between calls. Maybe we could also use `:track-position?`.

**Comment by borkdude** [comment]
I've investigated using `:track-position?` (on every call to `z/edn` except in `get` and `get-in`). This does help! But... track-position resets the position to `[1 1]`. So when you pass a sub-node, e.g. `{:b 2}` from `{:a {:b 2}}` then key `:b` would start at location `[1 1]` instead of `[1 5]` or so.

An alternative would be to implicitly go from nodes to strings and then re-parse to have accurate locations.

/cc @lread - as discussed on slack, it'd be nice if you could look at this at one point, as we would maybe move this lib to rewrite-clj proper one day.

**Comment by lread** [comment]
I am happy to have a peek sometime @borkdude!

**Comment by lread** [comment]
Ok, I'm starting to look at this issue and am at a point where I understand your observations.

Here are some ideas:

## Option 1: Update docs only

Tell users to compensate when they want to issue multiple operations:

```Clojure
(require '[borkdude.rewrite-edn :as r])

(-> "{}"
    r/parse-string
    (r/assoc-in [:deps 'foo] {:mvn/version "x"})
    str r/parse-string  ;; user compensation between ops
    (r/assoc-in [:deps 'bar] {:mvn/version "y"})
    str
    println)
{:deps {foo {:mvn/version "x"}
        bar {:mvn/version "y"}}}
```

Pros:
- Easy for us

Cons:
- A bit icky for users

## Option 2: Rework to have ops update positional (row/col) metadata

```Clojure
(-> "{}"
    r/parse-string
    (r/assoc-in [:deps 'foo] {:mvn/version "x"})
    (r/assoc-in [:deps 'bar] {:mvn/version "y"})
    str
    println)
{:deps {foo {:mvn/version "x"}
        bar {:mvn/version "y"}}}
```

This could be an internal updated-node -> str -> parse-string prior to op returns.

Pros:
- Non-breaking

Cons:
- Perhaps performance, but by how much, and does this matter for rewrite-edn?

## Option 3: breaking: work with positional zipper

Currently, inputs and outputs are rewrite-clj nodes.
If instead inputs and outputs were rewrite-clj positional zippers, we'd have to rework code, but we'd preserve and update our positional metadata throughout our operations.

Pros:
- No need to convert to str and reparse between ops.
- Operations could be applied to a subset of some larger positional zipper.

Cons:
- a bigger rewrite
- breaking for users who rely on rewrite-clj nodes for whatever reason
- likely a performance hit, but by how much, and does this matter for rewrite-edn?

## Proposal

I'm thinking option 2 is an easy non-breaking fix.
Unless you have other ideas, I'll start down that road to see if it has some nuances/problems I have not thought of yet.

**Comment by borkdude** [comment]
Thanks for digging into this. Perhaps the API functions should only go from string input to string output, so users could emit `r/parse-string` as well? We could do a best-effort attempt to reduce breakage.

I'm also open to making a breaking change by return a positional zipper which the user then has to convert back into a string. Both options sound good to explore, also bearing in mind that this could be an exercise before this stuff gets moved back into rewrite-clj.

**Comment by lread** [comment]
> Thanks for digging into this.

My pleasure, thanks for following up!

> Perhaps the API functions should only go from string input to string output, so users could emit `r/parse-string` as well?

Assuming you meant "omit" instead of "emit". So we'd have:

```Clojure
(-> "{}"
    (r/assoc-in [:deps 'foo] {:mvn/version "x"})
    (r/assoc-in [:deps 'bar] {:mvn/version "y"})
    println)
{:deps {foo {:mvn/version "x"}
        bar {:mvn/version "y"}}}

```

I was wondering about that too but saw `sexpr` in the rewrite-edn API and thought folks were maybe expecting to be working with nodes somewhere/somehow?

> I'm also open to making a breaking change by return a positional zipper which the user then has to convert back into a string. Both options sound good to explore, also bearing in mind that this could be an exercise before this stuff gets moved back into rewrite-clj.

About moving this back into rewrite-clj... I'm wondering now if it might be best left here as a separate lib. My thinking is that because rewrite-clj doesn't, by default, do any row/col position tracking, it also doesn't attempt to do much in the way of formatting. 

For example, the rewrite-clj zip API has an `assoc`, but it doesn't attempt nicey nicey vertical alignment.

I like the vertical alignment formatting rewrite-edn does, but that also implies position tracking. If I were to meld these ops back into rewrite-clj, they might require the position tracking zipper and that could be considered confusing to users. Or maybe not. Thoughts?

**Comment by borkdude** [comment]
`sexpr` is only exposed for convenience, in case you wanted to turn the return value into a form.

Right, I'm ok leaving the stuff here as well, so at least we can more freely experiment.

**Comment by lread** [comment]
If I wanted to point rewrite-clj users to rewrite-edn, I'd probably like rewrite-edn to be talking in zippers, not nodes or strings. 

The `rewrite-clj.zip.assoc` docstring could have a "see rewrite-edn for an assoc (and other related ops) that support vertical alignment".

But... that work could also happen at some later date under a new `borkdude.rewrite-edn.zip` namespace without breaking the current rewrite-edn API.

**Comment by lread** [comment]
I think we are intertwingling 2 speparate issues here: 
1. fixing the NPE
1. exploring usability from rewrite-clj

I'll tackle the first issue via Option 2, if that works for you.
I might raise a separate issue for usability from rewrite-clj.

**Comment by borkdude** [comment]
Sounds good to me

**Comment by borkdude** [comment]
> I'll tackle the first issue via Option 2, if that works for you.

@lread Were you still going to do this? I can also do this if you want

**Comment by lread** [comment]
Oh yeah, forgot about this! Can do sometime my-today.
