### ISSUE TITLE
Add minimal CI?

### ISSUE THREAD

**Issue by lread** [borkdude/rewrite-edn#22]
I can't offer the full `bb publish` treatment at this point but I can offer auto-test running on commits and PRs.

GitHub Actions work for you?

**Comment by borkdude** [comment]
A minimal GHA will do. Thanks for the offer!

**Comment by lread** [comment]
Cool, will start with ubuntu only, jdk8 only, default clojure version only.
We can add a matrix at some later date if we see a need.
