### ISSUE TITLE
Add operations for manipulating list/vec? e.g. conj

### ISSUE THREAD

**Issue by zerg000000** [borkdude/rewrite-edn#31]
When we dealing with edn, we will always encounter updating list/vector. It would be good to have some ops for that.

Since `conj` is not always worked as expected. Don't know what would be the best to add to the api.

**Comment by borkdude** [comment]
@zerg000000 I think it's usually best to take a few examples into account so we can see how it should work.

**Comment by zerg000000** [comment]
For example, I want to append `:create-friends-table` to the end of vector
```clojure
{:migrations [:init-db
              :create-user-table
              :create-role-tables]}
```

In rewrite-edn, can i do something like?

```clojure
(require '[rewrite-clj.zip :as z])

(-> (r/parse-string edn-string)
    (r/update :migrations (fn [vals] (z/append-child vals :create-friends-table)))
```

or 

```clojure
(-> (r/parse-string edn-string)
    (r/update :migrations (fn [vals] (r/append-child vals :create-friends-table)))
```

**Comment by borkdude** [comment]
@zerg000000 Ah yes, this works:

``` clojure
user=>        (def nodes (r/parse-string "{:a [1 2 3]}"))
#'user/nodes
user=>        (str (r/update nodes :a (fn [vals] (z/root (z/append-child (z/edn vals) 4)))))
"{:a [1 2 3 4]}"
```

**Comment by zerg000000** [comment]
That's nice. I can live with this, any plan make this ops as part of rewrite-edn api?

**Comment by borkdude** [comment]
I guess we could introduce `conj` but this would raise the expectation that it would work for list, vector, maps and sets and behave differently for each. The most frequent use case would be vector probably.

**Comment by borkdude** [comment]
Yeah, let's do `conj`.

**Comment by borkdude** [comment]
It might take me a while to add so if someone is willing to do a PR, welcome.
